Scan all owners repo
xrstf/github_exporter pull request #2
Opened 2022-08-18 08:08 UTC by ad2ien

Hi,
This PR because we needed a way to scan all the repos owned by an organization without having to set them one by one.
It's still possible monitor additional repos adding -repo flags

In future it could be nice to be able to select private or public repo, set the project number limit. So far : the first 100 public and private, not forked projects.

2022-08-19 17:46 UTC, xrstf requested changes
Cool beans :-) Can you please update the usage info in the README (just the `-help` code block)?

2022-08-22 06:25 UTC, ad2ien commented
> Cool beans :-) Can you please update the usage info in the README (just the `-help` code block)?

Hi, it's done, thanks.

2022-08-22 08:22 UTC, merged

2022-08-22 08:22 UTC, xrstf commented
Thanks a bunch :)

2023-01-20 18:56 UTC, u001920 commented
Hi, this implementation be listed in release version 0.3.3?